import type { Metadata } from "next";
import Link from "next/link";
import { ResetWelcome } from "@/components/reset-welcome";

export const metadata: Metadata = { title: "About", description: "About IQRA and its approach to sourced Qur’an learning." };

export default function AboutPage() {
  return <div className="shell narrow section-pad"><header className="page-header"><p className="eyebrow">Where Every Journey Begins</p><h1 className="page-title">About IQRA</h1><p>IQRA is a minimal learning companion for reading, listening to, understanding, and reflecting on the Qur’an through clearly identified sources.</p><blockquote className="verse mt-8"><p>“Read in the name of your Lord who created.”</p><cite>— Qur’an 96:1</cite></blockquote></header><div className="prose-page">
    <section><h2>Created by Arzoo</h2><p>IQRA was created by Arzoo to support thoughtful Qur’an reading, listening, understanding, and steady personal learning.</p></section>
    <section><h2>The meaning behind IQRA</h2><p>“Iqra” means “read” or “recite.” It is the opening command of Qur’an 96:1 and expresses the purpose behind this calm place to begin learning.</p></section>
    <section><h2>Content principles</h2><p>Qur’anic Arabic is never generated or altered. Translation, transliteration, audio, tafsir, and editorial reflection are labelled distinctly. Uncertain revelation reports are not presented as settled fact, and differing scholarly views are acknowledged.</p></section>
    <section id="sources-and-methodology"><h2>Sources and Content Methodology</h2><p>Compact metadata for all 114 Surahs is stored locally from Al Quran Cloud so browsing and search do not depend on a live request. Prepared Qur’anic Arabic uses its Uthmani edition, whose terms identify curation sources including Tanzil and Quran Academy and require the orthography and diacritics to remain unchanged.</p><p>Version 1 uses Saheeh International consistently for prepared English translation and Al Quran Cloud’s English Transliteration edition as a separate, clearly labelled layer. Translation rights remain with the rights-holder, so IQRA stores it only for carefully reviewed Surahs and always attributes it.</p><p><strong>Word-by-word dataset:</strong> islamic.app Word-by-word Quran, provided by islamic.app from Quran.com API v4 data. It documents coverage of all 114 Surahs, 6,236 ayahs, and 77,429 words; islamic.app attributes the Quran.com / Tarteel data under AGPL-3.0. IQRA requests only the ayah a reader opens, then validates the Surah number, ayah number, word count, Arabic, meaning, uniqueness, and ordered positions before display. It never splits Arabic or creates fallback meanings. Last reviewed: 21 July 2026.</p><p>Recitation is streamed—not stored—from the Islamic Network CDN, using Mishary Rashid Alafasy as the single Version 1 reciter. Provider terms permit educational streaming while recitation copyright remains with the reciter or rights-holder.</p><p>Tafsir summaries are short editorial explanations based on the cited scholarly source. Reflection prompts are IQRA editorial material, visibly separate from Qur’an, translation, and tafsir.</p></section>
    <section><h2>Personal learning data</h2><p>My Qur’an Journey stores identifiers, list settings, and progress locally in your browser. IQRA does not upload the contents of personal Learning Lists.</p></section>
    <section><h2>Learn with trusted guidance</h2><p>IQRA is a learning aid, not a religious authority. Qur’anic text, translations, historical claims, and tafsir content should be checked against trusted scholarly sources and discussed with qualified teachers when deeper guidance is needed.</p></section>
  </div><div className="about-actions"><Link href="/surahs/112" className="button-primary focus-ring">Study Al-Ikhlas</Link><Link href="/my-journey" className="button-secondary focus-ring">Open My Journey</Link><ResetWelcome /></div></div>;
}
