import type { SourceAttribution } from "@/types/quran";

export const QURAN_SOURCES = {
  arabic: { contentType: "quran-text", sourceName: "Al Quran Cloud — Uthmani edition", sourceDescription: "Uthmani Qur’anic Arabic curated from sources including Tanzil and Quran Academy.", licenseOrUsageNote: "Al Quran Cloud permits faithful reproduction with source acknowledgement; orthography and diacritics must not be altered.", externalReference: "https://alquran.cloud/terms-and-conditions" },
  translation: { contentType: "translation", sourceName: "Saheeh International", sourceDescription: "English translation delivered as the en.sahih edition by Al Quran Cloud.", licenseOrUsageNote: "Attribution is required. Rights remain with the translation rights-holder; this project does not expand stored translation content beyond reviewed Surahs without further review.", externalReference: "https://alquran.cloud/terms-and-conditions" },
  transliteration: { contentType: "transliteration", sourceName: "Al Quran Cloud — English Transliteration", sourceDescription: "Latin-script transliteration delivered as the en.transliteration edition.", licenseOrUsageNote: "Displayed with edition attribution; retained locally only for carefully prepared Surahs.", externalReference: "https://alquran.cloud/api" },
  wordByWord: { contentType: "word-by-word", sourceName: "islamic.app Word-by-word Quran", sourceDescription: "Uthmani word tokens, romanized transliteration, and concise English word meanings sourced by islamic.app from Quran.com API v4 data. Coverage: all 114 Surahs and 6,236 ayahs. Last reviewed: 21 July 2026.", licenseOrUsageNote: "islamic.app attributes its Quran.com / Tarteel Quran data under AGPL-3.0. Tokens are displayed unchanged with visible source attribution.", externalReference: "https://docs.islamic.app/api-reference/words" },
  audio: { contentType: "audio", sourceName: "Islamic Network CDN", sourceDescription: "Mishary Rashid Alafasy recitation streamed from the provider CDN.", licenseOrUsageNote: "Provider terms permit free educational streaming; copyrights remain with the reciter or rights-holder.", externalReference: "https://alquran.cloud/terms-and-conditions" },
  tafsir: { contentType: "tafsir", sourceName: "Tafsir Ibn Kathir (Abridged), Quran.com", sourceDescription: "Cited scholarly source underlying IQRA’s concise editorial summary for Al-Ikhlas.", licenseOrUsageNote: "IQRA stores a short attributed summary, not a reproduced full tafsir. Further reuse requires rights review.", externalReference: "https://quran.com/112:1/tafsirs/en-tafisr-ibn-kathir" },
  editorial: { contentType: "editorial", sourceName: "IQRA editorial content", sourceDescription: "Learning prompts written for reflection and visually separated from Qur’an and tafsir.", licenseOrUsageNote: "Not a religious ruling or substitute for qualified scholarly guidance.", externalReference: "/about" },
} as const satisfies Record<string, SourceAttribution>;
